version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: burger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fla85192502
    ports:
      - "5432:5432"